//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeiXinUI.sms {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.106jiekou.com/", ConfigurationName="sms.smsSoap")]
    public interface smsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.106jiekou.com/Submit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode Submit(string account, string password, string mobile, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.106jiekou.com/Submit", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> SubmitAsync(string account, string password, string mobile, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.106jiekou.com/ChangePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ChangePassword(string account, string password, string newpassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.106jiekou.com/ChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ChangePasswordAsync(string account, string password, string newpassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.106jiekou.com/GetNum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetNum(string account, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.106jiekou.com/GetNum", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetNumAsync(string account, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.106jiekou.com/VersionInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string VersionInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.106jiekou.com/VersionInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> VersionInfoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface smsSoapChannel : WeiXinUI.sms.smsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class smsSoapClient : System.ServiceModel.ClientBase<WeiXinUI.sms.smsSoap>, WeiXinUI.sms.smsSoap {
        
        public smsSoapClient() {
        }
        
        public smsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public smsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode Submit(string account, string password, string mobile, string content) {
            return base.Channel.Submit(account, password, mobile, content);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> SubmitAsync(string account, string password, string mobile, string content) {
            return base.Channel.SubmitAsync(account, password, mobile, content);
        }
        
        public string ChangePassword(string account, string password, string newpassword) {
            return base.Channel.ChangePassword(account, password, newpassword);
        }
        
        public System.Threading.Tasks.Task<string> ChangePasswordAsync(string account, string password, string newpassword) {
            return base.Channel.ChangePasswordAsync(account, password, newpassword);
        }
        
        public string GetNum(string account, string password) {
            return base.Channel.GetNum(account, password);
        }
        
        public System.Threading.Tasks.Task<string> GetNumAsync(string account, string password) {
            return base.Channel.GetNumAsync(account, password);
        }
        
        public string VersionInfo() {
            return base.Channel.VersionInfo();
        }
        
        public System.Threading.Tasks.Task<string> VersionInfoAsync() {
            return base.Channel.VersionInfoAsync();
        }
    }
}
